import "./globals.css";
import type { Metadata } from "next";
import { Berkshire_Swash } from "next/font/google";
import { NextAuthProvider } from "./website/components/providers/providers";

const berkish = Berkshire_Swash({
  weight: "400",
  style: "normal",
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Tudar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={berkish.className}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
